import { Inject, Injectable } from "@nestjs/common";
import { PrismaService } from "../../shared/prisma.service";
import { timeAsync } from "../../shared/perf";
import { getRequestContext } from "../../shared/request-context";
import { renderBaseEmail } from "./email.template";
import { NotificationQueue } from "./notification.queue";
import { EMAIL_PROVIDER, EmailProvider, WHATSAPP_PROVIDER, WhatsAppProvider } from "./notification.types";

export type InAppPayload = {
  userId: string;
  title: string;
  body: string;
  type: string;
  processId?: string;
};

export type WebhookEmailDraft = {
  target: "client" | "operator" | "both";
  to?: string;
  subject: string;
  text: string;
  html: string;
  from?: string;
  replyTo?: string;
};

export type WebhookPayload = {
  // Generic "link/otp" style payload (AuthService)
  email?: string;
  whatsapp?: string;
  link?: string;
  otp?: string;

  // Generic notification payload
  reason: string;
  channel?: "email" | "whatsapp" | "system";
  to?: string;
  subject?: string;
  body?: string;
  html?: string;
  audience?: "client" | "operator" | "unknown";
  requestedBy?: { email?: string; role?: string };

  // Rich email drafts for n8n to dispatch (ProcessService, AuthService)
  emails?: {
    client?: WebhookEmailDraft;
    operator?: WebhookEmailDraft;
    both?: WebhookEmailDraft;
  };

  // Optional structured process metadata (kept flexible on purpose)
  process?: Record<string, unknown>;
};

@Injectable()
export class NotificationService {
  constructor(
    private readonly queue: NotificationQueue,
    @Inject(EMAIL_PROVIDER)
    private readonly emailProvider: EmailProvider,
    @Inject(WHATSAPP_PROVIDER)
    private readonly whatsappProvider: WhatsAppProvider,
    private readonly prisma: PrismaService
  ) {}

  private async resolveAudience(email: string) {
    try {
      const user = await this.prisma.user.findUnique({ where: { email } });
      if (!user) return "client";
      return user.role === "MASTER" || user.role === "OPERATOR" ? "operator" : "client";
    } catch {
      return "unknown";
    }
  }

  async sendEmail(to: string, subject: string, body: string) {
    try {
      const inline = (process.env.NOTIFY_INLINE ?? "false") === "true";
      const { html, text } = renderBaseEmail({ title: subject, body });
      const from = process.env.EMAIL_FROM ?? "no-reply@fundarmf.local";
      const replyTo = process.env.EMAIL_REPLY_TO?.trim() || undefined;
      const correlationId = getRequestContext()?.correlationId;
      if (inline) {
        await timeAsync("externalMs", async () => {
          await this.emailProvider.sendEmail(to, subject, text);
        });
      } else {
        await timeAsync("externalMs", () =>
          this.queue.enqueueEmail({
            to,
            subject,
            text,
            html,
            from,
            replyTo,
            correlationId
          })
        );
      }

      const audience = await this.resolveAudience(to);
      const emailDraftClient: WebhookEmailDraft = { target: "client", to, subject, text, html, from, replyTo };
      const emailDraftOperator: WebhookEmailDraft = { target: "operator", to, subject, text, html, from, replyTo };
      const emailDraftBoth: WebhookEmailDraft = { target: "both", to, subject, text, html, from, replyTo };
      void this.sendWebhook({
        channel: "email",
        to,
        subject,
        body: text,
        html,
        audience,
        reason: "notification_sent",
        emails: {
          // Mirror the exact message for n8n to be able to send it too.
          client: audience === "client" ? emailDraftClient : undefined,
          operator: audience === "operator" ? emailDraftOperator : undefined,
          both: audience === "unknown" ? emailDraftBoth : undefined
        }
      });
    } catch (err) {
      console.error("[notify] sendEmail failed", err);
    }
  }

  /**
   * Sends a pre-rendered email draft (html + text) without re-wrapping it.
   * Useful for "process event" notifications that include CTA buttons.
   */
  async sendEmailDraft(
    to: string,
    draft: { subject: string; text: string; html: string; from?: string; replyTo?: string }
  ) {
    try {
      const inline = (process.env.NOTIFY_INLINE ?? "false") === "true";
      const from = draft.from ?? (process.env.EMAIL_FROM ?? "no-reply@fundarmf.local");
      const replyTo = draft.replyTo ?? (process.env.EMAIL_REPLY_TO?.trim() || undefined);
      const correlationId = getRequestContext()?.correlationId;

      if (inline) {
        // Inline provider API only supports "body text"; HTML/CTA will be regenerated by the provider.
        await timeAsync("externalMs", async () => {
          await this.emailProvider.sendEmail(to, draft.subject, draft.text);
        });
      } else {
        await timeAsync("externalMs", () =>
          this.queue.enqueueEmail({
            to,
            subject: draft.subject,
            text: draft.text,
            html: draft.html,
            from,
            replyTo,
            correlationId
          })
        );
      }

      // Webhook mirror: keep the exact draft so n8n can replay it.
      const audience = await this.resolveAudience(to);
      void this.sendWebhook({
        channel: "email",
        to,
        subject: draft.subject,
        body: draft.text,
        html: draft.html,
        audience,
        reason: "notification_sent",
        emails: {
          client:
            audience === "client"
              ? {
                  target: "client",
                  to,
                  subject: draft.subject,
                  text: draft.text,
                  html: draft.html,
                  from,
                  replyTo
                }
              : undefined,
          operator:
            audience === "operator"
              ? {
                  target: "operator",
                  to,
                  subject: draft.subject,
                  text: draft.text,
                  html: draft.html,
                  from,
                  replyTo
                }
              : undefined,
          both:
            audience === "unknown"
              ? {
                  target: "both",
                  to,
                  subject: draft.subject,
                  text: draft.text,
                  html: draft.html,
                  from,
                  replyTo
                }
              : undefined
        }
      });
    } catch (err) {
      console.error("[notify] sendEmailDraft failed", err);
    }
  }

  async sendWhatsApp(to: string, body: string) {
    try {
      const inline = (process.env.NOTIFY_INLINE ?? "false") === "true";
      const correlationId = getRequestContext()?.correlationId;
      if (inline) {
        await timeAsync("externalMs", async () => {
          await this.whatsappProvider.sendWhatsApp(to, body);
        });
      } else {
        await timeAsync("externalMs", () =>
          this.queue.enqueueWhatsApp({
            to,
            body,
            correlationId
          })
        );
      }
    } catch (err) {
      console.error("[notify] sendWhatsApp failed", err);
    }
  }

  async sendWebhook(payload: WebhookPayload) {
    const enabled = (process.env.N8N_WEBHOOK_ENABLED ?? "true") === "true";
    const url = process.env.N8N_WEBHOOK_URL?.trim();
    if (!enabled || !url) return;

    const correlationId = getRequestContext()?.correlationId;
    const secret = process.env.N8N_WEBHOOK_SECRET;
    const controller = new AbortController();
    const timeoutMs = Number(process.env.N8N_WEBHOOK_TIMEOUT_MS ?? 5000);
    const timeout = setTimeout(() => controller.abort(), timeoutMs);

    try {
      const response = await fetch(url, {
        method: "POST",
        headers: {
          "content-type": "application/json",
          ...(secret ? { "x-webhook-secret": secret } : {}),
          ...(correlationId ? { "x-correlation-id": correlationId } : {})
        },
        body: JSON.stringify({
          ...payload,
          correlationId
        }),
        signal: controller.signal
      });
      if (!response.ok) {
        const text = await response.text().catch(() => "");
        // Include URL to confirm the deployed env var value (Render sometimes keeps old values until a redeploy/restart).
        const preview = text.length > 800 ? `${text.slice(0, 800)}...` : text;
        console.warn("[notify] webhook failed", response.status, url, preview);
      }
    } catch (err) {
      console.warn("[notify] webhook error", url, err);
    } finally {
      clearTimeout(timeout);
    }
  }

  async createInApp(payload: InAppPayload) {
    return this.prisma.userNotification.create({
      data: {
        userId: payload.userId,
        processId: payload.processId,
        title: payload.title,
        body: payload.body,
        type: payload.type
      }
    });
  }

  async listInApp(userId: string, limit = 50, offset = 0) {
    const take = Number.isFinite(limit) && limit > 0 ? Math.min(limit, 200) : 50;
    const skip = Number.isFinite(offset) && offset > 0 ? offset : 0;
    return this.prisma.userNotification.findMany({
      where: { userId },
      orderBy: { createdAt: "desc" },
      take,
      skip
    });
  }

  async unreadCount(userId: string) {
    return this.prisma.userNotification.count({
      where: { userId, readAt: null }
    });
  }

  async markRead(userId: string, notificationId: string) {
    const result = await this.prisma.userNotification.updateMany({
      where: { id: notificationId, userId },
      data: { readAt: new Date() }
    });
    return { ok: result.count > 0 };
  }
}
