"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { api } from "@/lib/api";
import { Button } from "@/components/Button";
import { Card } from "@/components/Card";

type Contract = { id: string; title: string; status: string; currentVersion: number; versions: Array<{ id: string; version: number; status: string; content: unknown }> };
type Process = { id: string; clientName?: string; clientEmail: string; contracts: Contract[] };
export default function CompletedProcessPage({ params }: { params: { id: string } }) {
  const [process, setProcess] = useState<Process | null>(null); const [selected, setSelected] = useState<Contract | null>(null); const [content, setContent] = useState(""); const [message, setMessage] = useState(""); const [uploading, setUploading] = useState(false); const [saveState, setSaveState] = useState<"salvo" | "alterado" | "salvando" | "erro">("salvo"); const dirtyRef = useRef(false);
  useEffect(() => { void api<Process>(`/completed-processes/${params.id}`).then(setProcess).catch((e) => setMessage(e instanceof Error ? e.message : "Erro ao carregar.")); }, [params.id]);
  function open(contract: Contract) { setSelected(contract); const version = contract.versions[0]; setContent(JSON.stringify(version?.content ?? { type: "doc", content: [] }, null, 2)); dirtyRef.current = false; setSaveState("salvo"); }
  async function save() { if (!selected || !dirtyRef.current) return; setSaveState("salvando"); try { const saved = await api<{ version: number }>(`/completed-processes/contracts/${selected.id}`, { method: "PUT", body: JSON.stringify({ content: JSON.parse(content), expectedVersion: selected.currentVersion }) }); setSelected((old) => old ? { ...old, currentVersion: saved.version } : old); dirtyRef.current = false; setSaveState("salvo"); setMessage("Versão salva."); } catch (e) { setSaveState("erro"); setMessage(e instanceof Error ? e.message : "Erro ao salvar."); } }
  useEffect(() => { if (!selected || !dirtyRef.current) return; const timer = window.setTimeout(() => void save(), 1200); return () => window.clearTimeout(timer); }, [content, selected]);
  useEffect(() => { const handler = (event: BeforeUnloadEvent) => { if (dirtyRef.current) { event.preventDefault(); event.returnValue = ""; } }; window.addEventListener("beforeunload", handler); return () => window.removeEventListener("beforeunload", handler); }, []);
  function updateEditor(next: string) { setContent(next); dirtyRef.current = true; setSaveState("alterado"); }
  function applyBlock(type: "paragraph" | "heading") { try { const doc = JSON.parse(content); if (doc.content?.[0]) { doc.content[0].type = type; if (type === "heading") doc.content[0].attrs = { level: 2 }; else delete doc.content[0].attrs; updateEditor(JSON.stringify(doc, null, 2)); } } catch { setMessage("Corrija o JSON estruturado antes de formatar."); } }
  async function createBlank() { try { const result = await api<Contract>(`/completed-processes/${params.id}/contracts/blank`, { method: "POST", body: JSON.stringify({ title: "Nova alteração contratual" }) }); setProcess((old) => old ? { ...old, contracts: [...old.contracts, result] } : old); open(result); } catch (e) { setMessage(e instanceof Error ? e.message : "Erro ao criar."); } }
  async function upload(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; const form = new FormData(); form.append("file", file); setUploading(true); try { const result = await api<Contract>(`/completed-processes/${params.id}/contracts/upload`, { method: "POST", body: form }); setProcess((old) => old ? { ...old, contracts: [...old.contracts, result] } : old); open(result); setMessage("Documento convertido e preservado como original."); } catch (e) { setMessage(e instanceof Error ? e.message : "Erro ao converter."); } finally { setUploading(false); event.target.value = ""; } }
  if (!process) return <main className="app-container py-12"><Link href="/operator/processos-finalizados">Voltar</Link><Card className="mt-6 p-6">{message || "Carregando..."}</Card></main>;
  return <main className="app-container flex min-h-screen flex-col gap-6 py-12"><Link href="/operator/processos-finalizados" className="text-sm font-semibold text-slate">Voltar para processos finalizados</Link><header><h1 className="text-3xl font-semibold">{process.clientName ?? "Processo finalizado"}</h1><p className="text-slate">{process.clientEmail}</p></header><Card className="p-6"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-semibold">Contratos e alterações contratuais</h2><div className="flex gap-2"><Button variant="accent" onClick={() => void createBlank()}>Novo documento em branco</Button><label className="cursor-pointer rounded-lg border border-ink/20 px-4 py-2 text-sm font-semibold text-ink">{uploading ? "Convertendo..." : "Enviar PDF/DOCX"}<input className="sr-only" type="file" accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={(event) => void upload(event)} disabled={uploading} /></label></div></div>{process.contracts.length === 0 && <p className="mt-4 text-sm text-slate">Nenhum documento ainda. Escolha uma das duas formas de iniciar.</p>}<div className="mt-4 grid gap-3">{process.contracts.map((contract) => <button key={contract.id} className="rounded-xl border border-ink/10 p-4 text-left hover:bg-cream" onClick={() => open(contract)}><span className="font-semibold">{contract.title}</span><span className="ml-3 text-xs text-slate">{contract.status} · v{contract.currentVersion}</span></button>)}</div></Card>{selected && <Card className="p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">Editor estruturado: {selected.title}</h2><p className="mt-1 text-sm text-slate">Conteúdo canônico JSON, com salvamento automático e bloqueio de versão desatualizada.</p></div><span role="status" className="text-sm text-slate">{saveState === "salvando" ? "Salvando..." : saveState === "salvo" ? "Salvo" : saveState === "erro" ? "Erro ao salvar" : "Alterações pendentes"}</span></div><div className="mt-4 flex gap-2"><Button variant="ghost" onClick={() => applyBlock("paragraph")}>Parágrafo</Button><Button variant="ghost" onClick={() => applyBlock("heading")}>Título</Button></div><textarea aria-label="Conteúdo estruturado editável" value={content} onChange={(e) => updateEditor(e.target.value)} className="mt-3 min-h-[360px] w-full rounded-xl border border-ink/20 bg-white p-4 font-mono text-sm" /><div className="mt-4 flex gap-3"><Button variant="accent" onClick={() => void save()}>Salvar agora</Button><Button variant="ghost" onClick={() => setSelected(null)}>Fechar</Button></div></Card>}{message && <p role="status" className="text-sm text-slate">{message}</p>}</main>;
}
